// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_jYRHrT3VbuZpDNwpyUHaNaO2oUxjes',
    appId: '1:945588906360:web:d4cfe1942a2635ca91808d',
    messagingSenderId: '945588906360',
    projectId: 'agriledger-fd203',
    authDomain: 'agriledger-fd203.firebaseapp.com',
    storageBucket: 'agriledger-fd203.firebasestorage.app',
    measurementId: 'G-JF49LSDSFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXssHuUEApDdpVrrqwX-pKLakVP9rozg',
    appId: '1:945588906360:android:9d4fd41e643b863091808d',
    messagingSenderId: '945588906360',
    projectId: 'agriledger-fd203',
    storageBucket: 'agriledger-fd203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGPAO7yEjKAvveCzpQuBHkOjOdxrFLkk',
    appId: '1:945588906360:ios:0c92237041dc95eb91808d',
    messagingSenderId: '945588906360',
    projectId: 'agriledger-fd203',
    storageBucket: 'agriledger-fd203.firebasestorage.app',
    iosBundleId: 'com.agriledger.agriledger',
  );
}
